let suggestions = ["Channel",
	"CodingLab",
	"CodingNepal",
	"YouTube",
	"YouTuber",
	"YouTube Channel",
	"Blogger",
	"Bollywood",
	"Vlogger",
	"Vechiles",
	"Facebook",
	"Freelancer",
	"Facebook Page",
	"Designer",
	"Developer",
	"Web Designer",
	"Web Developer",
	"Login Form in HTML & CSS",
	"How to learn HTML & CSS",
	"How to learn JavaScript",
	"How to became Freelancer",
	"How to became Web Designer",
	"How to start Gaming Channel",
	"How to start YouTube Channel",
	"What does HTML stands for?",
	"What does CSS stands for?",
	"womens clothes",
	"80s fashion",
	"fashion designing",
	"fashion designer",
	"fashion blog",
	"mens fashion",
	"fashion designer games",
	"fashion house",
	"fashion show",
	"fashion week",
	"fashion tv",
	"new york fashion week",
	"fashion dresses",
	"fashion model",
	"fashion style",
	"fashion magazine",
	"korean fashion",
	"men fashion",
	"fashion 2016",
	"new fashion",
	"london fashion week",
	"fashion illustration",
	"fashion trends",
	"women fashion",
	"Aloo gobi",
	"Aloo tikki", "Aloo matar", "Baati", "Bhatura", "Bhindi masala", "Biryani", "Chaat", "Chapati", "Chole bhature", "Poha", "Fara", "phirni", "French bean aloo", "Gajar ka halwa", "Gajar matar aloo", "Gobhi matar", "Imarti", "Jalebi", "Kachori", "Kadai paneer", "Kadhi pakoda", "Kheer", "Khichdi", "Kofta", "Makki ki roti", "sarson da saag", "Mixed vegetable", "Murgh musallam", "Mushroom matar", "Naan", "Palak paneer", "Pani puri", "Panjeeri", "Papad", "Paratha", "Phirni", "Pindi chana", "Rajma chaval", "Rajma", "Samosa", "Shahi paneer", "Shahi tukra", "Singhada halwa", "Tandoori Chicken", "Avial", "Halwa", "Bisi bele bath ", "Bonda", "Goli bajje", "Hyderabadi biryani", "Idiappam", "Idli", "Kanji", "Masala Dosa", "Sambar", "Barfi", "Basundi", "Bhakri", "Bombil fry", "Chevdo", "Dabeli", "Dhokla", "Gatta curry", "Gulab jamun", "Jeera Aloo", "Panipuri", "Patra", "Poori", "Puri Bhaji", "Sabudana Khichadi", "Shakarpara", "Namakpara", "Shankarpali", "Shiro", "Sohan papdi", "Sutarfeni", "Thalipeeth", "Thepla", "Undhiyu", "Vada pav", "Vindaloo", "Sabudana khichri", "Sabudana vada", "Sakinalu", "Samosa", "Sandwich", "Upma", "Aam panna", "Aamras", "sugarcane juice", "Jal-jeera", "Jigarthanda", "Lemonade", "Rooh Afza", "Sharbat", "Adai", "Appam", "Baati", "Bhakri", "Chapati", "Cheela", "Masala dosa", "Rava dosa", "Neer dosa", "Rava idli", "Kachori", "Khakhra", "Kulcha", "Luchi", "Keema naan", "Papadum", "Gobhi paratha", "Laccha paratha", "Porotta", "Pathiri", "Phulka", "Chakuli pitha", "bhapa pithe", "Patishapta", "Chitoi Pithe", "Poi", "Akki rotti", "Rumali rotti", "Sanna", "Sheermal", "Taftan", "Tandoori roti", "Kori Rotti", "Litti", "Cham cham", "Chhena kheeri", "Misti doi", "Rabri", "Ras malai", "Rasgulla", "Sandesh", "Balushahi", "Kaju katli", "Kalakand", "Kulfi", "Lassi", "Motichoor laddu", "Nankhatai", "Petha", "Sheera", "Sohan halwa", "Chikki", "Dharwad Pedha", "Palkova", "Palathalikalu", "Khubani ka meetha", "Kesari bat", "Bebinca", "Puran poli", "Sutar feni", "Rogan josh ", "Aab gosh ", "Kabab ", "Mutton Curry", "Chhena kheeri", "Khoya paneer", "Mattar paneer", "Palak paneer", "Rasgula", "Dal", "Gobi manchurian", "Idiyappam", "bhelpuri", "ragda-pattice", "panipuri", "Butter chicken", "Chana masala", "Chicken rezala", "Chicken Tikka", "Dum aloo", "green peas daal", "Methi saag,", "Mushroom do pyaza", "Navrattan korma", "Paneer butter masala", "Paneer tikka masala", "Sattu ki roti", "Sooji halwa", "Tandoori Fish Tikka", "Maach Jhol", "Pork Bharta", "Sandige", "Batata Saung", "Dahi vada", "Dudhi no halwo", "Dum aaloo", "Pav Bhaji", "Penda", "Sev khamani", "Sev mamra", "Fruit juice", "Gud-nimbu sharbat ", "Kala Khatta", "Kesar kasturi", "Coconut water", "Pudina sharbat ", "Sattu paani", "Saunf paani", "Chili parotha", "Dhebra", "Butter naan", "Aloo paratha", "Pesarattu bread", "Arisa Pitha", "Pulla Attu", "Ragi dosa", "Ragi rotti", "Coconut Barfi", "Arisa Pitha", "Apple Halwa", "Mutton Kasha", "Bamboo Mutton ", "Mutton Besar", "Kosha mangsho", "Thoran", "Biriyani", "Chinese bhel"]